apiVersion: v1
kind: Service
metadata:
  name: k8sphotoappapiusers
  labels:
    name: k8sphotoappapiusers
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: k8sphotoappapiusers
  type: LoadBalancer