apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sphotoappapiusers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8sphotoappapiusers
  template:
    metadata:
      labels:
        app: k8sphotoappapiusers
    spec:
      containers:
        - name: k8sphotoappapiusers
          image: vijayakrishnajava/k8sphotoappapiusers
          imagePullPolicy: Never
          ports:
            - containerPort: 8080