apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: vijayakrishnajava/k8sphotoappapiusers
      jib: {}
  local: {}

deploy:
  kubectl:
    manifests:
      - k8s-role.yaml
      - k8s-config.yaml
      - k8s-deployment-local.yaml
      - k8s-service.yaml
